// Generated by Xata Codegen 0.29.4. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "ItemSKU",
    columns: [
      { name: "Item_Name", type: "int" },
      { name: "Description", type: "text" },
      { name: "Case_Pack_QTY", type: "int" },
      { name: "Case_GTIN", type: "int" },
      { name: "End_Of_Life", type: "bool" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type ItemSKU = InferredTypes["ItemSKU"];
export type ItemSKURecord = ItemSKU & XataRecord;

export type DatabaseSchema = {
  ItemSKU: ItemSKURecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://brianhess-s-workspace-51oml8.us-west-2.xata.sh/db/LicensePlate",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
